title: My Blog
email: broersa@gmail.com
description: >
  This is the place I write about my experiments with technology. Enjoy..
baseurl: ""
url: "https://broersa.github.io"
twitter_username: broersa
github_username:  broersa

markdown: kramdown
theme: minima
